Solution.Presentation/Areas/Document/Controllers/Request/AssignController.cs
using iDAS.Presentation.Controllers;
using iDAS.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net;
using Ext.Net.MVC;
using iDAS.Service.Common;
using iDAS.Presentation.Common;

namespace iDAS.Presentation.Areas.Document.Controllers
{
    public class AssignController : FrontController
    {
        public ActionResult Index()
        {
            return new Ext.Net.MVC.PartialViewResult { };
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult GetData()
        {
            try
            {
                var data = DocumentRequestService.GetDataAssignArea().ToList();
                return this.Store(data);
            }
            catch (Exception)
            {
                return this.Direct();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult GetTableData(StoreRequestParameters param, iDAS.Service.Common.Resource.RequestStatus status = Service.Common.Resource.RequestStatus.All)
        {
            try
            {
                var pageIndex = param.Page;
                var pageSize = param.Limit;
                var count = 0;
                var data = DocumentRequestService.GetDataCreateByAssigner(pageIndex, pageSize, out count, status).ToList();
                return this.Store(data, count);
            }
            catch (Exception)
            {
                return this.Direct();
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult GetDepartmentData()
        {
            try
            {
                var data = DepartmentService.GetAll().ToList();
                return this.Store(data);
            }
            catch (Exception)
            {
                return this.Direct();
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Save(DocumentRequestBO request)
        {
            var result = false;
            try
            {
                DocumentRequestService.SaveAssign(request.NewRequest);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch
            {
                this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Send(DocumentRequestBO request)
        {
            var result = false;
            try
            {
                DocumentRequestService.SendAssign(request.NewRequest);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch
            {
                this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        /// <summary>
        /// Yêu cầu soạn thảo xuất phát bởi yêu cầu
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RequestWrite(Guid? id)
        {
            ViewData["lstTypeRequestWriteDocument"] = iDAS.Service.Common.Resource.GetRequestStatus();
            var model = new DocumentRequestBO()
            {

            };
            return new Ext.Net.MVC.PartialViewResult { ViewData = ViewData, Model = model };
        }
        /// <summary>
        /// Yêu cầu soạn thảo xuất phát bởi đề nghị
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RequestWriteBySuggest(Guid? id)
        {
            ViewData["lstTypeRequestWriteDocument"] = iDAS.Service.Common.Resource.GetRequestStatus();
            var model = new DocumentRequestBO()
            {
            };
            return new Ext.Net.MVC.PartialViewResult { ViewData = ViewData, Model = model };
        }
        /// <summary>
        /// Yêu cầu soạn thảo xuất phát bởi đề nghị
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Revert(Guid id)
        {
            var result = false;
            try
            {
                DocumentRequestService.RevertAssign(id);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch
            {
                this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(Guid id)
        {
            var result = false;
            try
            {
                DocumentRequestService.Delete(id);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch
            {
                this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Destroy(Guid id)
        {
            var result = false;
            try
            {
                DocumentRequestService.DestroyAssign(id);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch
            {
                this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        #region Phân công

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isSuggest"></param>
        /// <returns></returns>
        public ActionResult AssignForm(Guid id, bool isSuggest)
        {
            try
            {
                var model = DocumentRequestService.GetAssignInfoByRequestId(id);
                var viewName = model.IsSuggest ? (model.TypeWrite == true ? "RequestWriteBySuggest" : "RequestAdjustBySuggest") : "RequestWrite";
                return new Ext.Net.MVC.PartialViewResult { Model = model, ViewName = viewName };
            }
            catch (Exception)
            {
                this.ShowNotify(Common.Resource.SystemFailure);
                return this.Direct();
            }
        }

        public ActionResult GetEmployeeRelation(Guid suggestId)
        {
            try
            {
                var data = DocumentWriteSuggestService.GetEmployeeRoleBySuggest(suggestId);
                return this.Store(data);
            }
            catch (Exception)
            {
                return this.Direct();
            }
        }

        #endregion

        #region Phân công tạo mới yêu cầu soạn thảo
        /// <summary>
        /// Form yêu cầu
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RequestWriteByAssigner(string id)
        {
            try
            {
                var model = DocumentRequestService.GetFormRequestWriteByAssigner(id);
                return new Ext.Net.MVC.PartialViewResult { ViewData = ViewData, Model = model };
            }
            catch (Exception)
            {
                this.ShowNotify(Common.Resource.SystemFailure);
                return this.Direct();
            }

        }
        /// <summary>
        /// Lưu yêu cầu
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult SaveRequestWriteByAssigner(DocumentRequestBO request)
        {
            var result = false;
            try
            {
                DocumentRequestService.SaveRequestWriteByAssigner(request);
                result = true;
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch (Exception ex)
            {
                if (ex is DataHasBeenExistedException)
                    this.ShowNotify(ex.Message);
                else
                    this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        /// <summary>
        /// Gửi yêu cầu
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult SendRequestWriteByAssigner(DocumentRequestBO request)
        {
            var result = false;
            try
            {
                DocumentRequestService.SendRequestWriteByAssigner(request);
                result = true;
                Notify(TitleResourceNotifies.RequestWriteDocument + " \""+request.Document.Name+"\"", request.Note, request.EmployeePerform.Id, UrlResourceNotifies.RequestWriteByAssigner, new { id = request.Id });
                this.ShowNotify(Common.Resource.SystemSuccess);
            }
            catch (Exception ex)
            {
                if (ex is DataHasBeenExistedException)
                    this.ShowNotify(ex.Message);
                else
                    this.ShowNotify(Common.Resource.SystemFailure);
            }
            return this.Direct(result: result);
        }
        public ActionResult RevertRequestWriteByAssigner(Guid id)
        {
            var result = false;
            try
            {

Solution.Presentation/Areas/Document/Views/Assign/RequestAdjustBySuggest.cshtml
@using Ext.Net;
@using Ext.Net.MVC;
@using iDAS.Presentation.Common;
@model iDAS.Service.DocumentRequestBO
@{
    var X = Html.X();
    var formId = X.GetComponentID();
}
@(X.Menu().ID("contextDocumentMenu")
 .Items(
            X.MenuItem().Text("Chi tiết").IconCls("x-fa fa-info-circle").Handler("onCreateRequest();"),
            X.MenuSeparator(),
            X.MenuItem().Text("Gửi").IconCls("x-fa fa-share").Handler("Ext.Msg.confirm('Xác nhận','Bạn có muốn gửi yêu cầu soạn thảo này đến người soạn thảo không?')"),
            X.MenuItem().Text("Thu hồi").IconCls("x-fa fa-reply").Handler("Ext.Msg.confirm('Xác nhận','Bạn có muốn thu hồi yêu cầu soạn thảo đã gửi không?')"),
            X.MenuSeparator(),
            X.MenuItem().Text("Xóa").IconCls("x-fa fa-trash-o").Handler("Ext.Msg.confirm('Xác nhận','Bạn có muốn xóa yêu cầu soạn thảo này không?')"),
            X.MenuItem().Text("Hủy").IconCls("x-fa fa-ban").Handler("Ext.Msg.confirm('Xác nhận','Bạn có muốn hủy yêu cầu soạn thảo này không?')")
    )
)
@(X.WindowFormat().Modal(false)
    .Listeners(
            ls =>
            {
                ls.BeforeShow.Handler = "this.setHeight(App.ctDesktop.getHeight());this.setWidth(App.ctDesktop.getWidth()*2/3); this.alignTo(App.ctDesktop,'tr-tr'); this.el.slideIn('r',{duration : 500});";
                ls.BeforeClose.Handler = "App.windowCompilation.el.slideOut('r',{duration : 500}); return false;";
            })
    .ID("windowRequestWriteBySuggest")
    .Padding(0).BodyPadding(0).Title("Đề nghị sửa đổi").IconCls("x-fa fa-pencil")
    .Items(
            X.PanelHbox()
            .BodyPadding(0)
            .Flex(1)
            .Border(false)
            .Header(false)
            .ID("tabRequest")
            .Frame(true)
            .StyleSpec("border: none;")
            .Items(
              X.FieldSetVBox().Title("Thông tin đề nghị").Padding(5).Flex(1).Margin(5)
              .Items(
              X.TextFieldDecodeFor(m => m.SuggestAdjust.EmployeeSuggestBy.Name).ID("txtSuggesterName").EmptyText(Resource.DocumentName).AllowBlank(false).HideLabel(true).Note(Resource.DocumentName).NoteAlign(NoteAlign.Top).ReadOnly(true),
                X.TextAreaDecodeFor(m => m.SuggestAdjust.ReasonOfSuggest).ID("txtSuggestDescription").Flex(1).HideLabel(true).EmptyText("Nội dung đề nghị").Note("Nội dung đề nghị").NoteAlign(NoteAlign.Top).MarginSpec("5 0 10 0").ReadOnly(true),
                X.ContainerHBox().Items(
                X.DateFieldFor(m => m.SuggestAdjust.EstimateAt).ID("txtSuggestEstimateAt").Flex(1).MarginSpec("0 0 5 0").HideLabel(true).Note("Ngày yêu cầu").NoteAlign(NoteAlign.Top).EmptyText("Ngày yêu cầu").Note("Ngày yêu cầu").NoteAlign(NoteAlign.Top).ReadOnly(true),
                X.DateFieldFor(m => m.SuggestAdjust.ApproveAt).MarginSpec("0 0 5 5").Flex(1).HideLabel(true).Note("Ngày duyệt").NoteAlign(NoteAlign.Top).EmptyText("Ngày duyệt").Note("Ngày duyệt").NoteAlign(NoteAlign.Top).ReadOnly(true)
                ),
                X.FieldSet()
                    .Padding(3)
                    .MarginSpec("5 0 0 0")
                    .Title("Người phê duyệt")
                    .Items(X.EmployeeFieldFor(m => m.EmployeeApproveBy).ID("txtEmployeePerform").AllowBlank(false).EmployeeReadOnly(true)),
                    X.TextAreaFor(m => m.SuggestAdjust.ApproveNote).HideLabel(true).EmptyText("Bút phê người phê duyệt").Note("Bút phê người phê duyệt").NoteAlign(NoteAlign.Top).MarginSpec("5 0 0 0").ReadOnly(true)
                ),
            X.FieldSetVBox().Title("Danh sách yêu cầu soạn thảo").Padding(5).MarginSpec("5 5 5 0").Flex(1)
            .Items(
                X.FormPanelVBoxFormat().ID(formId)
                    .Items(
                        X.HiddenFor(m => m.NewRequest.TypeCompile).Value(true),
                        X.HiddenFor(m => m.NewRequest.Id),
                        X.HiddenFor(m => m.NewRequest.ParentId),
                        X.HiddenFor(m => m.NewRequest.TypeWrite).Value(Model.TypeWrite),
                        X.HiddenFor(m => m.NewRequest.TypeAdjust).Value(Model.TypeAdjust),
                        X.HiddenFor(m => m.NewRequest.DocumentId),
                        X.HiddenFor(m => m.NewRequest.DepartmentId).Value(Model.DepartmentId),
                        X.TextAreaDecodeFor(m => m.NewRequest.Note).Flex(1).HideLabel(true).EmptyText("Nội dung yêu cầu soạn thảo").Note("Nội dung yêu cầu soạn thảo").NoteAlign(NoteAlign.Top).MarginSpec("5 0 10 0"),
                        X.FileUploadFieldFor(m => m.NewRequest.FileAttachs).ID("fileNewRequestAttachment").MarginSpec("5 0 0 0").Note("Đính kèm"),
                        X.FieldSet().Padding(3).MarginSpec("5 0 0 0").Title("Thời gian soạn thảo")
                            .Items(
                                X.ContainerHBox().Items(
                                X.DateFieldFor(m => m.NewRequest.StartAt).Flex(1).HideLabel(true).EmptyText("Ngày bắt đầu").Note("Ngày bắt đầu").NoteAlign(NoteAlign.Top).MarginSpec("0 0 5 0"),
                                X.DateFieldFor(m => m.NewRequest.EndAt).MarginSpec("0 0 5 5").Flex(1).HideLabel(true).EmptyText("Ngày kết thúc").Note("Ngày kết thúc").NoteAlign(NoteAlign.Top)
                                )),
                         X.DocumentEmployeeFieldFor(m => m.NewRequest.EmployeePerform, iDAS.Service.Common.Resource.DocumentTypeProcess.WriteAndRelation, departmentId: Model.DepartmentId.ToString(),
                              setHidden: true,
                             startRole: iDAS.Service.Common.Resource.DocumentProcessRole.AssignmentWriteAndEdit)
                        ))
                   )
           )
           .Buttons(
                X.Button().ID("btnTransfer").Text("Chuyển phân công").IconCls("x-fa fa-refresh").Hidden(Model.NewRequest.IsSend == true).OnClientClick("onTransfer(this.up('window').id, this.id);"),
                    X.Button().ID("btnDestroy").Text("Hủy").IconCls("x-fa fa-recycle").Hidden(Model.NewRequest.IsSend != true)
                    .DirectEvents(
                                de =>
                                {
                                    de.Click.Method = HttpMethod.POST;
                                    de.Click.Confirmation.ConfirmRequest = true;
                                    de.Click.Confirmation.Message = Resource.ConfirmDestroy;
                                    de.Click.Confirmation.Title = Resource.Confirm;
                                    de.Click.Confirmation.BeforeConfirm = "Ext.Msg.buttonText.yes='" + Resource.ConfirmYes + "'; Ext.Msg.buttonText.no='" + Resource.ConfirmNo + "';";
                                    de.Click.Before = "this.up('window').down('#loadMask').show(); this.up('window').down('#loadMaskEmpty').hide(); this.setDisabled(true);";
                                    de.Click.Url = Url.Action("Destroy", "Assign");
                                    de.Click.ExtraParams.Add(new { id = Model.NewRequest.Id });
                                    de.Click.Success = "App.storeAssignment.reload(); this.up('window').doDestroy();";
                                }),
                    X.Button().ID("btnRevert").Text("Thu hồi").IconCls("x-fa fa-reply").Hidden(Model.NewRequest.IsSend != true)
                    .DirectEvents(
                                de =>
                                {
                                    de.Click.Method = HttpMethod.POST;
                                    de.Click.Confirmation.ConfirmRequest = true;
                                    de.Click.Confirmation.Message = Resource.ConfirmRevert;
                                    de.Click.Confirmation.Title = Resource.Confirm;
                                    de.Click.Confirmation.BeforeConfirm = "Ext.Msg.buttonText.yes='" + Resource.ConfirmYes + "'; Ext.Msg.buttonText.no='" + Resource.ConfirmNo + "';";
                                    de.Click.Before = "this.up('window').down('#loadMask').show(); this.up('window').down('#loadMaskEmpty').hide(); this.setDisabled(true);";
                                    de.Click.Url = Url.Action("Revert", "Assign");
                                    de.Click.ExtraParams.Add(new { id = Model.NewRequest.Id });
                                    de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                                }),
                    X.ButtonDelete().Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Delete", "Assign");
                        de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                    }),
                    X.ButtonSend().FormID(formId).Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Send", "Assign");
                        de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                    }),
                        X.ButtonSave().FormID(formId).Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Save", "Assign");
                    }),
                    X.ButtonExit()
           )
)
<script>
    var onCreateRequest = function () {
        var url = '@Url.Action("CreateRequestWrite", "Request")';
        onDirectMethod(url, null);
    };
    var itemContextMenuPosition = function (grid, record, item, index, e, eOpts) {
        e.stopEvent();
        App.contextDocumentMenu.showAt(e.getX(), e.getY() - 50);
    };
    var onTransfer = function (containerId, btnId) {
        var fromWindow = 'windowRequestWriteBySuggest';
        var requestId = '@Model.Id';
        var params = { requestId: requestId, containerId: containerId, alignTo: btnId, fromWindow: fromWindow };
        var url = '@Url.Action("Form", "Transfer")';
        onDirectMethod(url, params);
    };

    var renderActorComlumn = function (value, meta, record) {
        var title = '<span style="margin-left: 44px;font-size:10px;">Tổng giám đốc</span></span>';
        var result = record.data.Name;
        var image = '<img src="' + record.data.PerformBy.AvatarUrl + '" style="margin-top: 2px; width: 30px; height: 30px; border-radius: 50%; position: absolute;border: 1px solid">';
        var name = '<span style="margin-left: 44px;">' + Ext.htmlEncode(record.data.PerformBy.Name) + '</span><br/>';
        result = '<span>' + image + name + title + '</span>';
        return result;
    };

</script>

Solution.Presentation/Areas/Document/Views/Assign/SuggestToAssignerBySuggestor.cshtml
@using Ext.Net;
@using Ext.Net.MVC;
@using iDAS.Presentation.Common;
@model iDAS.Service.DocumentRequestBO
@{
    var X = Html.X();
    var formId = X.GetComponentID();
}

@(X.WindowFormat()
    .Modal(false)
    .Listeners(
            ls =>
            {
                ls.BeforeShow.Handler = "this.setHeight(App.ctDesktop.getHeight());this.setWidth(App.ctDesktop.getWidth()*2/3); this.alignTo(App.ctDesktop,'tr-tr'); this.el.slideIn('r',{duration : 500});";
                ls.BeforeClose.Handler = "App.windowCompilation.el.slideOut('r',{duration : 500}); return false;";
            })
    .ID("windowRequestWriteBySuggest")
    .Padding(0)
    .BodyPadding(0)
    .Title("Đề nghị viết mới")
    .IconCls("x-fa fa-pencil")
    .Items(
            X.PanelHbox()
            .BodyPadding(0)
            .Flex(1)
            .Border(false)
            .Header(false)
            .ID("tabRequest")
            .Frame(true)
            .StyleSpec("border: none;")
            .Items(
              X.FieldSetVBox().Title("Thông tin đề nghị").Padding(5).Flex(1).Margin(5)
              .Items(
                X.TextFieldDecodeFor(m => m.Suggest.EmployeeSuggestBy.Name).ID("txtSuggesterName").EmptyText(Resource.DocumentName).AllowBlank(false).HideLabel(true).Note(Resource.DocumentName).NoteAlign(NoteAlign.Top).ReadOnly(true),
                X.DateFieldFor(m => m.Suggest.EstimateAt).ID("txtSuggestEstimateAt").HideLabel(true).Note("Ngày đề nghị").NoteAlign(NoteAlign.Top).EmptyText("Ngày đề nghị").Note("Ngày đề nghị").NoteAlign(NoteAlign.Top).ReadOnly(true),
                X.TextAreaDecodeFor(m => m.Suggest.ReasonOfSuggest).ID("txtSuggestDescription").Flex(1).HideLabel(true).EmptyText("Nội dung đề nghị").Note("Nội dung đề nghị").NoteAlign(NoteAlign.Top).MarginSpec("5 0 10 0").ReadOnly(true)
                ),
            X.FieldSetVBox()
            .Title("Thông tin yêu cầu soạn thảo")
            .Padding(5)
            .MarginSpec("5 5 5 0")
            .Flex(1)
            .Items(
                X.FormPanelVBoxFormat().ID(formId)
                    .Items(
                        X.HiddenFor(m => m.NewRequest.TypeCompile).Value(true),
                        X.HiddenFor(m => m.NewRequest.Id),
                        X.HiddenFor(m => m.NewRequest.ParentId),
                        X.HiddenFor(m => m.NewRequest.TypeWrite).Value(Model.TypeWrite),
                        X.HiddenFor(m => m.NewRequest.TypeAdjust).Value(Model.TypeAdjust),
                        X.HiddenFor(m => m.NewRequest.RequestSource).Value(Model.RequestSource),
                        X.HiddenFor(m => m.NewRequest.DocumentId),
                        X.HiddenFor(m => m.NewRequest.DepartmentId).Value(Model.DepartmentId),
                        X.TextAreaDecodeFor(m => m.NewRequest.Note).Flex(1).HideLabel(true).EmptyText("Nội dung yêu cầu soạn thảo").Note("Nội dung yêu cầu soạn thảo").NoteAlign(NoteAlign.Top).MarginSpec("5 0 10 0"),
                        X.FileUploadFieldFor(m => m.NewRequest.FileAttachs).ID("fileNewRequestAttachment").MarginSpec("5 0 0 0").Note("Đính kèm"),
                        X.FieldSet().Padding(3).MarginSpec("5 0 0 0").Title("Thời gian soạn thảo")
                            .Items(
                                X.ContainerHBox().Items(
                                X.DateFieldFor(m => m.NewRequest.StartAt).Flex(1).HideLabel(true).EmptyText("Ngày bắt đầu").Note("Ngày bắt đầu").NoteAlign(NoteAlign.Top).MarginSpec("0 0 5 0"),
                                X.DateFieldFor(m => m.NewRequest.EndAt).MarginSpec("0 0 5 5").Flex(1).HideLabel(true).EmptyText("Ngày kết thúc").Note("Ngày kết thúc").NoteAlign(NoteAlign.Top)
                                )),
                         X.DocumentEmployeeFieldFor(m => m.NewRequest.EmployeePerform, iDAS.Service.Common.Resource.DocumentTypeProcess.WriteAndRelation, departmentId: Model.DepartmentId.ToString())
                        )
                        )
                   )
           )
           .Buttons(
                X.Button().ID("btnTransfer").Text("Chuyển phân công").IconCls("x-fa fa-refresh").Hidden(Model.NewRequest.IsSend == true).OnClientClick("onTransfer(this.up('window').id, this.id);"),
                    X.Button().ID("btnDestroy").Text("Hủy").IconCls("x-fa fa-recycle").Hidden(Model.NewRequest.IsSend != true)
                    .DirectEvents(
                                de =>
                                {
                                    de.Click.Method = HttpMethod.POST;
                                    de.Click.Confirmation.ConfirmRequest = true;
                                    de.Click.Confirmation.Message = Resource.ConfirmDestroy;
                                    de.Click.Confirmation.Title = Resource.Confirm;
                                    de.Click.Confirmation.BeforeConfirm = "Ext.Msg.buttonText.yes='" + Resource.ConfirmYes + "'; Ext.Msg.buttonText.no='" + Resource.ConfirmNo + "';";
                                    de.Click.Before = "this.up('window').down('#loadMask').show(); this.up('window').down('#loadMaskEmpty').hide(); this.setDisabled(true);";
                                    de.Click.Url = Url.Action("Destroy", "Assign");
                                    de.Click.ExtraParams.Add(new { id = Model.NewRequest.Id });
                                    de.Click.Success = "App.storeAssignment.reload(); this.up('window').doDestroy();";
                                }),
                    X.Button().ID("btnRevert").Text("Thu hồi").IconCls("x-fa fa-reply").Hidden(Model.NewRequest.IsSend != true)
                    .DirectEvents(
                                de =>
                                {
                                    de.Click.Method = HttpMethod.POST;
                                    de.Click.Confirmation.ConfirmRequest = true;
                                    de.Click.Confirmation.Message = Resource.ConfirmRevert;
                                    de.Click.Confirmation.Title = Resource.Confirm;
                                    de.Click.Confirmation.BeforeConfirm = "Ext.Msg.buttonText.yes='" + Resource.ConfirmYes + "'; Ext.Msg.buttonText.no='" + Resource.ConfirmNo + "';";
                                    de.Click.Before = "this.up('window').down('#loadMask').show(); this.up('window').down('#loadMaskEmpty').hide(); this.setDisabled(true);";
                                    de.Click.Url = Url.Action("Revert", "Assign");
                                    de.Click.ExtraParams.Add(new { id = Model.NewRequest.Id });
                                    de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                                }),
                    X.ButtonDelete().Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Delete", "Assign");
                        de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                    }),
                    X.ButtonSend().FormID(formId).Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Send", "Assign");
                        de.Click.Success = "App.storeAssignment.reload(); WindowSlideOut(this.up('window'));";
                    }),
                        X.ButtonSave().FormID(formId).Hidden(Model.NewRequest.IsSend == true)
                    .DirectEvents(de =>
                    {
                        de.Click.Url = Url.Action("Save", "Assign");
                    }),
                    X.ButtonExit()
           )
)
<script>

    var onTransfer = function (containerId, btnId) {
        var fromWindow = 'windowRequestWriteBySuggest';
        var requestId = '@Model.Id';
        var params = { requestId: requestId, containerId: containerId, alignTo: btnId, fromWindow: fromWindow };
        var url = '@Url.Action("Form", "Transfer")';
        onDirectMethod(url, params);
    };

</script>